{% set name = "runpynb" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6cc75b365acbac68949c53b23ccaf7ee588299a90c418d925d260ed8368031a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - nbconvert
    - nbformat
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - runpynb

about:
  home: https://github.com/lsys/runPyNB
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Run (and time) Jupyter Notebooks for command-line and makefile
  doc_url: http://runpynb.rtfd.io/
  dev_url: https://github.com/lsys/runPyNB

extra:
  recipe-maintainers:
    - lsys
